export enum RoleType {
  NEW_EMPLOYEE = 'NEW_EMPLOYEE',
  NEW_MANAGER = 'NEW_MANAGER',
  MANAGER_FOR_NEW_EMPLOYEE = 'MANAGER_FOR_NEW_EMPLOYEE',
  MANAGER_FOR_NEW_MANAGER = 'MANAGER_FOR_NEW_MANAGER',
}
